---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healet
  namespace: healet
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: healet
  spec:
      containers:
      - name: app
        image: zenitugo/healet
        ports:
        - containerPort: 80