---
apiVersion: v1
kind: Service
metadata:
  name: healet-svc
selector:
  name: healet  
  labels:
    name: healet
  namespace: healet
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079 
