---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healet-deployment
  namespace: healet
spec:
  replicas: 1   
  selector:
    matchLabels:
      type: front-end
      app: healetapp
  template:
    metadata:
      labels:
        type: front-end
        app: healetapp
    spec:
      containers:
        - name: healet
          image: zenitugo/healet
          ports:
            - containerPort: 80
