---
apiVersion: v1
kind: Service
metadata:
  name: healet-external-service
  namespace: healet
spec:
  selector:
    app: healetapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    

