---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: p1v
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-00a2bcc7f05d2e752
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: p2v
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0e538b6af82bf8d75
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain