name: Destroy Terraform Resources

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to Perform'
        required: true
        default: 'destroy'

jobs:
  terraform_destroy:
    name: "Terraform Destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add steps to setup Terraform, configure credentials, and destroy resources
      # ...
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Destroy Terraform Resources
        id: destroy
        run: terraform destroy -auto-approve 